name: Enhance Audio
on:
  workflow_dispatch:
    inputs:
      input:
        description: "File audio (relative to repo root)"
        required: true
        default: "input.wav"

jobs:
  enhance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/cache@v4
        with:
          path: ~/.cache
          key: voice-models-${{ runner.os }}

      - run: pip install -e .
      - run: pip install deepfilternet voicefixer pedalboard pyloudnorm
      - run: python main.py "${{ inputs.input }}"

      - uses: actions/upload-artifact@v4
        with:
          name: enhanced-audio
          path: output/
